---
repos:
  - repo: local
    hooks:
      - id: go-build
        name: Go Build
        entry: bash -c 'GOEXPERIMENT=greenteagc CGO_ENABLED=0 GOOS=linux go build -a -ldflags='-w -s' -installsuffix cgo -o /tmp/s3dbdump ./'
        language: system
        types: [go]
        pass_filenames: false
      - id: go-mod-tidy
        name: Go Mod Tidy
        entry: go mod tidy
        language: system
        types: [go]
        pass_filenames: false
      - id: go-vet
        name: Go Vet
        entry: go vet ./...
        language: system
        types: [go]
        pass_filenames: false
      - id: go-test
        name: Go Test
        entry: go test ./...
        language: system
        types: [go]
        pass_filenames: false
