---
name: Integration Test

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  issues: read
  pull-requests: read

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: testpass123
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: testpass123
    steps:
      - uses: actions/checkout@v7

      - name: Integration test
        run: bash scripts/integration-test.sh
