---
name: Integration Test

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  issues: read
  pull-requests: read

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: testpass123
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: testpass123
      minio:
        image: quay.io/minio/minio:latest-cicd
        ports:
          - 9000:9000
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio123
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: minio123    
    steps:
      - uses: actions/checkout@v7

      - name: Integration test
        run: bash scripts/integration-test.sh
